baseURL: "http://thien-nguyen.xyz/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Thien Nguyen
icon: icon.png
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Blogs
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Categories
                  url: tags/
                  weight: 10
                - name: About Me
                  url: about/
                  weight: 20
                # - name: WiKi
                #   url: https://github.com/adityatelange/hugo-PaperMod/wiki/
                # - name: Discord
                #   url: https://discord.gg/ahpmTvhVmp

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Theme PaperMod
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: Thien Nguyen
        imageUrl: "headshot.jpg"
        imageTitle: profile picture
        imageWidth: 220
        imageHeight: 220
        subtitle: "💻 Software Developer @ Tyson Foods | 🤖 Deep Learning | 🧑‍💻 Full-stack development"
        buttons:
            - name: Blogs
              url: archives
            - name: Categories
              url: tags
            - name: About me
              url: about

    socialIcons:
        - name: github
          url: "https://github.com/canhthienkt"
        - name: linkedin
          url: "https://www.linkedin.com/in/thien-nguyen98/"

    editPost:
        URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link
    
    aboutMe:
        enable: true
        image: "headshot.jpg"

    label:
        text: "Thien Nguyen"
        icon: headshot.jpg
        iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "apple-touch-icon.png"
        image: "headshot.jpg"
    #     safari_pinned_tab: "<link / abs url>"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: true # hide on single page

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

